services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - netraiss

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - netraiss

networks:
  netraiss:
    driver: bridge