services:
  backend:
    build:
      context: ./netbackend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./netfrontend
    ports:
      - "5173:5173"
    env_file:
      - ./netfrontend/.env
    depends_on:
      - backend